FROM node:22-slim AS builder
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build


FROM node:22-slim AS runner
WORKDIR /app
COPY --from=builder /app/.next .next
COPY --from=builder /app/public public
COPY package*.json .
RUN npm ci --omit=dev
EXPOSE 3000
CMD ["npm", "run", "start"]